### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: SNAKE_CASE

### ISSUE THREAD

**Issue by paries** [plivo/plivo-java#104]
Trying to run a very simple send using the example docs
When i try to run it i get the error

`Exception in thread "main" java.lang.NoSuchFieldError: SNAKE_CASE
	at com.plivo.api.PlivoClient.<init>(PlivoClient.java:91)
	at com.plivo.api.PlivoClient.<init>(PlivoClient.java:182)
	at com.plivo.api.Plivo.init(Plivo.java:12)
	at com.unitnet.virtAssist.test.PLivoTest.main(PLivoTest.java:14)`

From My pom.xml
`<dependency>
            <groupId>com.plivo</groupId>
            <artifactId>plivo-java</artifactId>
            <version>4.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.9</version>
        </dependency>`

Please advise

**Comment by huzaif-plivo** [comment]
@paries We were unable to replicate the error specified. Therefore we request you to try out our latest version([4.14.0](https://github.com/plivo/plivo-java/releases/tag/v4.14.0)) by following the code mentioned [here](https://www.plivo.com/docs/sms/guides/send-sms#code). Feel free to contact the [support team](support.plivo.com/hc/en-us) for any issues.
