### ISSUE TITLE
loop parameter is not working in CallPlayCreator

### ISSUE THREAD

**Issue by pranay-lonkar** [plivo/plivo-java#105]
- **loop** parameter is not working in **CallPlayCreator**.
- It is not playing the audio file in a loop even when this parameter is set as true.
- **Version 4.4.1**

**Comment by huzaif-plivo** [comment]
@pranay-lonkar The issue isn’t reproducible even with the specified version of SDK, if you are still experiencing the same we request you to contact our [support team](https://support.plivo.com/hc/en-us) at any time along with the samples.

**Comment by huzaif-plivo** [comment]
@pranay-lonkar The issue isn’t reproducible even with the specified version of SDK, if you are still experiencing the same we request you to contact our [support team](https://support.plivo.com/hc/en-us) at any time along with the samples.
