### ISSUE TITLE
mix parameter in CallPlayCreator is not working properly

### ISSUE THREAD

**Issue by pranay-lonkar** [plivo/plivo-java#106]
- **mix** parameter in **CallPlayCreator** is not working properly.
- As per the Plivo documentation, if this is set to false then participants of the call would not be able to hear anyone speaking in the call until the Play is stopped.
- But I am able to hear a voice on both legs if I set it as **false**.
- It works when I set it as **true**.
- **Version 4.4.1**

**Comment by nixonsam** [comment]
@pranay-lonkar this is fixed in our recent releases, please use our latest release. Thank you!
