### ISSUE TITLE
Remove reliance on internal modules and replace with standalone libraries (avoid NoClassDefFoundError)

### ISSUE THREAD

**Issue by burtonrhodes** [plivo/plivo-java#115]
Upgrading from v4.1.0 -> v4.4.3 gives me an error (using OpenJDK 11): 
java.lang.NoClassDefFoundError: com/sun/xml/internal/bind/marshaller/CharacterEscapeHandler 

Does it makes sense to remove dependencies on internal modules and replace them with their standalone libraries?  Especially with JDK 11 in wider circulation:  http://openjdk.java.net/jeps/320

**Comment by huzaif-plivo** [comment]
@burtonrhodes We have fixed this and released this patch in the latest [release](https://github.com/plivo/plivo-java/releases/tag/v4.15.0), please feel free to contact our [support team](https://support.plivo.com/hc/en-us) in case of any questions or concerns.
