### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by Stexxen** [plivo/plivo-java#12]
Hi Any chance you could update the maven repository?

http://mvnrepository.com/artifact/com.plivo/plivo-java

The last change to master was 2 months ago, but the pom.xml was 5 months ago and says v3.0.4, so should that be 3.0.5 with the post 3.0.4 changes? The repo still says 3.0.1

The Changelog is also showing different details.

Thanks,
S.

**Comment by varunvairavan** [comment]
@Stexxen @rkolias This was done a while back.
