### ISSUE TITLE
Unable to add time filters in Get detials API for sms and call

### ISSUE THREAD

**Issue by Ramya-Raghu** [plivo/plivo-java#14]
The given format is the docs for time filter is YYYY-MM-DD HH:MM[:ss[.uuuuuu]]. Java does not accept spaces here and always errors out.
Using "2015-07-26%2011%3A47"  format works though. 
The library is not url encoding the parameters.

**Comment by varunvairavan** [comment]
Fixed in [3.0.7](https://github.com/plivo/plivo-java/commit/a7f826f23fbe98ab4390009241508ce432e5f63f)
