### ISSUE TITLE
Add ability to set Log level

### ISSUE THREAD

**Issue by martinisraelsen** [plivo/plivo-java#147]
Referencing https://github.com/plivo/plivo-java/issues/32, it would be great to have a way to set the logging level.

**Comment by MrThreepwood** [comment]
Yeah, this is logging some fairly questionable stuff by default. I'm not sure how logging is handled in this library, and I'm not sure why it's not respecting java standard logging pacakages (SLF4J). We may have to drop this SDK because of the logging.

**Comment by huzaif-plivo** [comment]
@martinisraelsen @MrThreepwood Thank you for the feedback!
This issue has been resolved in [v5.8.0](https://github.com/plivo/plivo-java/releases/tag/5.8.0) (https://github.com/plivo/plivo-java/releases/tag/5.8.0). It allows user to customize the logging preferences to their own development needs. From [here](https://www.plivo.com/docs/sdk/server/java-sdk#log-level), you can see an example of how to set these preferences. Feel free to contact our [support-team](https://support.plivo.com/hc/en-us) for any queries.
