### ISSUE TITLE
NoClassDefFoundError: retrofit2/Converter$Factory

### ISSUE THREAD

**Issue by bchristman30** [plivo/plivo-java#35]
Hello, 
I've downloaded the plivo-java-4.0.0.beta-1.jar and included it in my project. 
when trying to run `Plivo.init()` the following exception is thrown. 

`SEVERE: Servlet.service() for servlet [p2p] in context with path [/p2p] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: retrofit2/Converter$Factory] with root cause
java.lang.ClassNotFoundException: retrofit2.Converter$Factory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1854)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1703)
	at com.plivo.api.Plivo.init(Plivo.java:11)`

it seems like the jar doesn't have all the necessary dependencies included? 
Am I missing something?

thanks,
brandon

**Comment by plivo-sdks** [comment]
@bchristman30 We don't have dependencies included in the JAR file for the v4 Beta versions. You will have to manually install these dependencies for now.
